### ISSUE TITLE
Double-check that user gets notification from group member, not from system

### ISSUE THREAD

**Issue by buildthomas** [roblox-dev-forum/dev-rel-automated-messages#6]

**Comment by Kampfkarren** [comment]
I believe DevRel has already made sure this works?

**Comment by buildthomas** [comment]
I recommend double-checking on this; I'm not 100% sure they tested that the notification actually has the right user listed, I think they just tested that it actually changes the owner of the message to a random devrel member

**Comment by Kampfkarren** [comment]
Doesn't, but too much work to fix.
